version: '3'

services:
  api:
    container_name: api
    build: ./api
    ports:
      - 3000:3000
    env_file:
      - ./api/.env
    depends_on:
      - db
  db:
    container_name: db
    image: mysql:8.0
    ports:
      - 3306:3306
    tty: true
    env_file:
      - ./db/.env
    volumes:
      - type: volume
        source: mysql-data
        target: /var/lib/mysql
      - type: bind
        source: ./db/init
        target: /docker-entrypoint-initdb.d

volumes:
  mysql-data:
    name: mysql-volume

